#!/bin/sh
echo
echo " Step 1: Removing existing packages "
echo "----------------------------------------"

if [ -d vendor ]; then
	rm -rf vendor/
else
	echo "The vendor/ directory appears to have already been removed."
fi

if [ -d bin ]; then
	rm -rf bin/
	mkdir bin/
else
	mkdir bin/
	echo "The bin/ directory appears to have already been removed."
fi

if [ -f composer.lock ]; then
	rm composer.lock
else
	echo "No composer.lock found. Assuming fresh composer install."
fi

echo
echo " Step 2: Removing reports "
echo "----------------------------------------"
if [ -d reports ]; then
	rm -rf reports/
	mkdir reports/
else
	mkdir reports/
	echo "The reports/ directory appears to have already been removed."
fi

echo "Cleanup complete."
