#!/bin/sh
echo "Running phpunit..."
wpgrade-checks/bin/phpunit --bootstrap wpgrade-system/tests/bootstrap.php --coverage-html wpgrade-checks/reports/code-coverage wpgrade-system
echo
echo 
read -p "Testing complete. Press any key to close... " -n1 -s